### ISSUE TITLE
How is tree shaking achieved?

### ISSUE THREAD

**Issue by pmulac** [qdouble/angular2webpack2-starter#82]
My understanding is that webpack 2 can tree shake code via the UglifyJs plugin only if you set `module: es2015` in the tsconfig.json.  This repo isn't doing this, so I'm wondering how tree shaking is possible here.

Moreover, [this issue](https://github.com/mishoo/UglifyJS2/issues/1261) with UglifyJS leads me to believe that tree shaking isn't currently possible when targeting es5.

Could you explain how tree shaking is achieved?

**Comment by qdouble** [comment]
All builds target es5 unless they will be again processed by some other program...sometimes you may see a build targeting es6 or es2015 so they can be processed by something else (i.e. rollup). These setting are not necessary when using webpack (even setting the lib to es5 instead of es6 is mitigated by using @core-js types, as the lib setting only effects the polyfills applied by typescript).

Having one bundle is the main thing that enables Webpack to do it's treeshaking (instead of separate vendor bundles) from my understanding. I compared this starter using rollup and final size was close to the same when including polyfills and everything else (maybe 10-20KB difference). If you add `compress:true` to the the UglifyJsPlugin here: https://github.com/qdouble/angular2webpack2-starter/blob/master/webpack.config.ts#L122, although it won't change the output size, you will see it log the unused functions and code that it is dropping, which I assume is the treeshaking that is silently occurring.
